title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://kwymer123.github.io/uhg-test-doc-site

aux_links:
  Template Repository: https://github.com/kwymer123/uhg-test-doc-site
